version: '3.9'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=embroidery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  backend:
    build: ./backend/
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"    
    depends_on:
      - db
  frontend:
    build: ./frontend/
    command: ng serve --host 0.0.0.0 --disableHostCheck true    
    depends_on:
      - backend
  nginx:
    build: ./nginx/
    ports:
      - 8080:80
    depends_on:
      - frontend